config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #resources :users , only: [:new, :create]
  resources :users
  resources :restaurants
  #resources :comments, except: [:new]
  resources :posts, except: [:new, :create] do
    resources :comments, only: [:index, :new, :create, :edit, :update, :destroy]
  end

  #get '/posts/:post_id/comments/new', to :'comments#new', as: 'new_comment'
  get '/posts/new/:id', to: 'posts#new', as:'new_post'
  post '/posts/:id', to: 'posts#create'

  get '/posts/:post_id/likes/new', to:'likes#new', as: 'post_like'
  post '/posts/:post_id/likes/new', to:'likes#create'

  delete '/posts/:post_id/likes/:id', to: 'likes#destroy'

  # post '/likes/:id', to: 'likes#create'
  # delete '/likes/:id', to: 'likes#delete'

  #get '/posts/:post_id/likes/new', to:'likes#new', as: 'new_like'
  

  # get '/comments/edit/:id', to: 'comments#edit', as:'edit_comment'
  # patch '/comments/:id', to: 'comments#update'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'

  get '/welcome' => 'welcome#home'
  get '/error' => 'welcome#error'
  get '/admin' => 'welcome#admin'

  get '/analytics' => 'analytics#index'


  root 'posts#index'
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    has_many :posts

    def self.total_count
        Restaurant.all.count
    end

    def self.restaurants_with_posts
        count = 0
        Restaurant.all.each do |restaurant|
            if restaurant.posts != []
                count += 1
            end
        end
        return count
    end
end

# def self.restaurants_with_posts_comments
#     count = 0
#     Restaurant.all.each do |restaurant|
#         if restaurant.posts != []
#             restaurant.posts.each do |post|
#                 if post.comments != [comment]
#                 count += 1
#                 end
#             end   
#         end
    
#     end
#     return count
# end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
    before_action :require_logged_in
    # before_action :admin_user
    before_action :admin_user , except: [:index, :show]
    def index
        @restaurants = Restaurant.all
    end

    def show 
        @restaurant = Restaurant.find(params[:id])  
    end

    def new
        @restaurant = Restaurant.new
    end
    
    def create
        @restaurant = Restaurant.new(restaurant_params)

        if @restaurant.save
            redirect_to @restaurant, notice: "Restaurant added successfully"
        else
            render "new"
        end
    end

    def edit
        # byebug
        @restaurant = Restaurant.find(params[:id])  
    end

    def update
        @restaurant = Restaurant.find(params[:id])
        @restaurant.update(restaurant_params)
        if @restaurant.save
          redirect_to @restaurant
        else
          render :edit
        end
    end

    def destroy
        @restaurant = Restaurant.find(params[:id])
        @restaurant.destroy
        flash[:notice] = "Restaurant deleted."
        redirect_to restaurants_path
    end

    def restaurant_params
        params.require(:restaurant).permit(
            :name, :description, :website, :phonenumber, :imageurl, :email
        )
    end
end

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant<%= @restaurant.name %></h1>

<%= form_for @restaurant  do |f| %>
  <%= f.label :name %><br>
  <%= f.text_field :name %> <br><br>

  <%= f.label :description %><br>
  <%= f.text_area :description %> <br><br>

  <%= f.label :website %><br>
  <%= f.text_area :website %> <br><br>
  
  <%= f.label :phonenumber %><br>
  <%= f.telephone_field :phonenumber %> <br><br>

  <%= f.label :imageurl %><br>
  <%= f.text_field :imageurl %> <br><br>

  <%= f.label :email %><br>
  <%= f.email_field :email, required: true %> <br><br>

  <%= f.submit %>
<% end %>

app/views/restaurants/index.html.erb
<h3><%= link_to "Create new restaurant", new_restaurant_path%></h3> 

<%@restaurants.each do |restaurant|%>
<%=link_to restaurant.name,  restaurant%> <br><br><br>
<%end%>

app/views/restaurants/new.html.erb
<h1>Create an Restaurant</h1>

<%= form_for @restaurant  do |f| %>
  <%= f.label :name %><br>
  <%= f.text_field :name %> <br><br>

  <%= f.label :description %><br>
  <%= f.text_area :description %> <br><br>

  <%= f.label :website %><br>
  <%= f.text_area :website %> <br><br>
  
  <%= f.label :phonenumber %><br>
  <%= f.telephone_field :phonenumber %> <br><br>

  <%= f.label :imageurl %><br>
  <%= f.text_field :imageurl %> <br><br>

  <%= f.label :email %><br>
  <%= f.email_field :email, required: true %> <br><br>

  <%= f.submit %>
<% end %>

​

app/views/restaurants/show.html.erb
<div class = "post_div">
<h3><%=@restaurant.name%></h3>
<%=@restaurant.description%> <br>

<ul>
 Phonenumber: <a href= "tel:#{@restaurant.website}">
         <%=@restaurant.phonenumber %>
      </a> <br>

Email: <%=mail_to @restaurant.email,@restaurant.email%><br>

Website: <%= link_to @restaurant.website %> <br>
</ul>

<br>
<img src=<%=@restaurant.imageurl%> alt=<%=@restaurant.imageurl%> height="100">

<br>

<%= link_to "make a post", new_post_path(@restaurant.id) %>

<%#= link_to "edit", edit_restaurant_path(@restaurant), :class => "postsbtn1" %>
<%= button_to "edit", edit_restaurant_path(@restaurant), method: :get,:class => "postsbtn1" %>
</div>