config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #resources :users , only: [:new, :create]
  resources :users
  resources :restaurants
  #resources :comments, except: [:new]
  resources :posts, except: [:new, :create] do
    resources :comments, only: [:index, :new, :create, :edit, :update, :destroy]
  end

  #get '/posts/:post_id/comments/new', to :'comments#new', as: 'new_comment'
  get '/posts/new/:id', to: 'posts#new', as:'new_post'
  post '/posts/:id', to: 'posts#create'

  get '/posts/:post_id/likes/new', to:'likes#new', as: 'post_like'
  post '/posts/:post_id/likes/new', to:'likes#create'

  delete '/posts/:post_id/likes/:id', to: 'likes#destroy'

  # post '/likes/:id', to: 'likes#create'
  # delete '/likes/:id', to: 'likes#delete'

  #get '/posts/:post_id/likes/new', to:'likes#new', as: 'new_like'
  

  # get '/comments/edit/:id', to: 'comments#edit', as:'edit_comment'
  # patch '/comments/:id', to: 'comments#update'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'

  get '/welcome' => 'welcome#home'
  get '/error' => 'welcome#error'
  get '/admin' => 'welcome#admin'

  get '/analytics' => 'analytics#index'


  root 'posts#index'
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments
    has_many :users, through: :comments
    belongs_to :restaurant

    has_many :likes
    has_many :users, through: :likes

    def self.total_count
        Post.all.count
    end

    def likes_count
        likes.length
    end

    def self.comment_count
        Post.all.length > 0 ? Post.all.map do |post|
            post.comments.length
        end.inject { |sum, n| sum + n } : 0 
    end    
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :require_logged_in
    before_action :admin_user , except: [:index, :show]
    def index
        @user = current_user
        @posts = Post.all
    end

    def new
        @post = Post.new
        @restaurant = Restaurant.find(params[:id])
    end

    def show
        @post = Post.find(params[:id])
    end
  
    def create
        @restaurant = Restaurant.find(params[:id])
        @post = Post.new(title: params[:post][:title], message: params[:post][:message], restaurant_id: @restaurant.id)
        @post.save
        redirect_to post_path(@post)
    end


    # private
    # def post_params
    #     params.require(:post).permit(:title, :message, :restaurant_id, :id)
    # end
end

app/views/posts/index.erb
<h1>Feed</h1>

<%@posts.each do |post|%>
<div class = "post_div">
<div class = "text_div">
<h3 class = "blue-text"> 
<%= link_to post.restaurant.name, restaurant_path(post.restaurant.id) %> </h3>  
<img src=<%=post.restaurant.imageurl%> alt=<%="@restaurant.imageurl"%> height="100" >
<h4> <%= post.title %> </h4>  

<h5> <%= post.message %> </h5> 

<% if session[:user_id] && @user.likes?(post) %>

<%= link_to "Unlike",post_like_path(post), method: :delete %>
<% else %>
<%= link_to "Likes",  post_like_path(post), method: :post %>
<% end %>
<%= post.likes.count%>

<div class = "message_div">

<%post.comments.each do |comment|%>
<img class= "message-image" src=<%=comment.user.imageurl%> alt=<%=@user.imageurl%> >
    <%=link_to comment.user.name, comment.user %>

   <%=comment.message%>  <br> 
 
   <%if comment.user.id == session[:user_id] %>
  
   
   <%= button_to "edit", edit_post_comment_path(post,comment), method: :get,:class => "postsbtn1" %>

  <%= button_to "delete", post_comment_path(post,comment), method: :delete, data: { confirm: 'are u sure lol' }, :class => "postsbtn1" %> 
 
   <%end%> 
    <%end%> <br>

</div>

<%= button_to "Add a comment", new_post_comment_path(post), method: :get, :class => "postsbtn1"%>
</div>
</div>
<%end%>

app/views/posts/new.html.erb
 <br>Make a Post  <br>
<%= form_for(@post, url: "/posts/#{@restaurant.id}" )  do |f| %>


  <%= f.label :title %><br>
  <%= f.text_field :title %> <br><br>

  <%= f.label :message %><br>
  <%= f.text_area :message  %>

 <%= f.submit %>
<% end %>

app/views/posts/show.html.erb
<div class = "post_div">

<h3> 
<%= @post.restaurant.name %> </h3>  
<img src=<%=@post.restaurant.imageurl%> alt=<%="@restaurant.imageurl"%> height="100" >
<h4> <%= @post.title %> </h4>  

<h5> <%= @post.message %> </h5> 

<div class = "message_div">

<%@post.comments.each do |comment|%>
<img class= "message-image" src=<%=comment.user.imageurl%> alt=<%=@user.imageurl%> >
    <%=comment.user.name + ": "%>
    
   <%=comment.message%>  <br> 
   <%if comment.user == session[:user_id] %>
   
   <%= button_to "edit", edit_post_comment_path(post,comment), method: :get,:class => "postsbtn1" %>

  <%= button_to "delete", post_comment_path(post,comment), method: :delete, data: { confirm: 'are u sure lol' }, :class => "postsbtn1" %> 
 
   <%end%> 
    <%end%> <br>

</div>