config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #resources :users , only: [:new, :create]
  resources :users
  resources :restaurants
  #resources :comments, except: [:new]
  resources :posts, except: [:new, :create] do
    resources :comments, only: [:index, :new, :create, :edit, :update, :destroy]
  end

  #get '/posts/:post_id/comments/new', to :'comments#new', as: 'new_comment'
  get '/posts/new/:id', to: 'posts#new', as:'new_post'
  post '/posts/:id', to: 'posts#create'

  get '/posts/:post_id/likes/new', to:'likes#new', as: 'post_like'
  post '/posts/:post_id/likes/new', to:'likes#create'

  delete '/posts/:post_id/likes/:id', to: 'likes#destroy'

  # post '/likes/:id', to: 'likes#create'
  # delete '/likes/:id', to: 'likes#delete'

  #get '/posts/:post_id/likes/new', to:'likes#new', as: 'new_like'
  

  # get '/comments/edit/:id', to: 'comments#edit', as:'edit_comment'
  # patch '/comments/:id', to: 'comments#update'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'

  get '/welcome' => 'welcome#home'
  get '/error' => 'welcome#error'
  get '/admin' => 'welcome#admin'

  get '/analytics' => 'analytics#index'


  root 'posts#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OpenKitchen</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class = "background_div">

<%if session[:user_id]%>
<a href="http://localhost:3000/posts">
<img class="header-logo center" src="https://dl.airtable.com/.attachmentThumbnails/2638db50408214b30540aac1b0c5eee1/4ce89b4c" alt="HTML5 Icon" >
</a>
<%= form_tag ({controller: 'sessions', action: 'destroy', method: 'post'}) do %>
  <input type=submit value='logout', class = "postsbtn1">
<% end %>
<%= link_to "All Restaurants", restaurants_path, :class => "postsbtn1"%>
<%= link_to "My Profile", user_path(session[:user_id])	, :class => "postsbtn1"%>
<%= link_to "Feed", posts_path, :class => "postsbtn1"%>
<%= link_to "Analytics", analytics_path, :class => "postsbtn1"%>
<%end%>


    <% flash.each do |name, msg| -%>
      <span class="blinking"><%= content_tag :div, msg, class: name %></span>
    <% end -%>


    
    <%= yield %>
  </body>
</html>